<?php
require_once __DIR__.'/auth.php'; require_login(); require_once __DIR__.'/modules.php'; require_once __DIR__.'/db.php'; require_once __DIR__.'/icons.php';
$pageTitle='Dashboard';
if(is_subadmin()){
 $today=date('Y-m-d');$id=current_member_id();$name=current_member_name();$allI=db_get_all('invoices');$allP=db_get_all('payments');$myI=array_values(array_filter($allI,fn($r)=>((string)($r['created_by_id']??'')===$id)||(strcasecmp(trim((string)($r['created_by']??'')),$name)===0)));$myP=array_values(array_filter($allP,fn($r)=>((string)($r['created_by_id']??'')===$id)||(strcasecmp(trim((string)($r['created_by']??'')),$name)===0)));$todaySelling=0;$todayCollection=0;$pending=0;$myNos=[];foreach($myI as $r){$myNos[$r['invoice_no']??'']=true;if(substr((string)($r['created_at']??$r['date']??''),0,10)===$today)$todaySelling+=(float)($r['amount']??0);$paid=0;foreach($allP as $p)if(($p['invoice_no']??'')===($r['invoice_no']??''))$paid+=(float)($p['amount']??0);$pending+=max(0,(float)($r['amount']??0)-$paid);}foreach($myP as $p)if(substr((string)($p['date']??$p['created_at']??''),0,10)===$today && (($p['invoice_no']??'')===''||isset($myNos[$p['invoice_no']??''])))$todayCollection+=(float)($p['amount']??0);
 require __DIR__.'/layout_top.php'; ?>
<main class="dashboard-page"><div class="kpi-grid dashboard-kpis"><div class="kpi-card"><div class="label">Today Selling</div><div class="value green">₹<?=number_format($todaySelling,2)?></div></div><div class="kpi-card"><div class="label">Today Collection</div><div class="value green">₹<?=number_format($todayCollection,2)?></div></div><div class="kpi-card"><div class="label">Total Pending</div><div class="value orange">₹<?=number_format($pending,2)?></div></div></div><div class="panel dashboard-modules-panel"><div class="panel-header"><h2>My Workspace</h2></div><div class="panel-body"><div class="module-grid dashboard-modules"><?php foreach(['leads','customers','quotations','invoices','tasks'] as $k):?><a class="module-tile" href="module.php?m=<?=$k?>"><div class="icon"><?=icon($MODULES[$k]['icon'],22)?></div><div class="name"><?=htmlspecialchars($MODULES[$k]['label'])?></div><div class="count"><?= $k === 'customers' ? 'Name & mobile only' : ($k === 'invoices' ? 'Own invoices' : ($k === 'quotations' ? 'Own quotations' : 'My access')) ?></div></a><?php endforeach;?></div></div></div></main><?php require __DIR__.'/layout_bottom.php';exit; }
// Main Admin dashboard — existing global KPIs
$data=db_load();$totalInvoiceAmt=0;$totalPaymentAmt=0;$cashCollected=0;$onlineCollected=0;foreach($data['invoices'] as $i){$totalInvoiceAmt+=(float)($i['amount']??0);}foreach($data['payments'] as $p){$totalPaymentAmt+=(float)($p['amount']??0);if(strcasecmp((string)($p['mode']??''),'cash')===0)$cashCollected+=(float)($p['amount']??0);else $onlineCollected+=(float)($p['amount']??0);} $totalPendingAmt=max(0,$totalInvoiceAmt-$totalPaymentAmt);$totalExpenseAmt=array_reduce($data['expenses'],fn($c,$e)=>$c+(float)($e['amount']??0),0);$openingBalance=10000.0;$cashExpenses=0;$onlineExpenses=0;foreach($data['expenses'] as $e){if(strcasecmp((string)($e['mode']??''),'online')===0)$onlineExpenses+=(float)($e['amount']??0);else $cashExpenses+=(float)($e['amount']??0);} $cashBalance=$cashCollected-$cashExpenses;$onlineBalance=$openingBalance+$onlineCollected-$onlineExpenses;
require __DIR__.'/layout_top.php'; ?>
<main class="dashboard-page"><div class="kpi-grid dashboard-kpis"><div class="kpi-card"><div class="label">Total Invoiced</div><div class="value">₹<?=number_format($totalInvoiceAmt,2)?></div></div><div class="kpi-card"><div class="label">Total Collected</div><div class="value green">₹<?=number_format($totalPaymentAmt,2)?></div></div><div class="kpi-card"><div class="label">Cash Balance</div><div class="value green">₹<?=number_format($cashBalance,2)?></div></div><div class="kpi-card"><div class="label">Online / Bank Balance</div><div class="value green">₹<?=number_format($onlineBalance,2)?></div></div><div class="kpi-card"><div class="label">Total Pending</div><div class="value orange">₹<?=number_format($totalPendingAmt,2)?></div></div></div><div class="panel dashboard-modules-panel"><div class="panel-header"><h2>Modules</h2></div><div class="panel-body"><div class="module-grid dashboard-modules"><?php foreach($MODULES as $k=>$item):?><a class="module-tile" href="module.php?m=<?=$k?>"><div class="icon"><?=icon($item['icon'],22)?></div><div class="name"><?=htmlspecialchars($item['label'])?></div></a><?php endforeach;?><a class="module-tile" href="subadmin.php"><div class="icon"><?=icon('customers',22)?></div><div class="name">Subadmin</div></a></div></div></div></main><?php require __DIR__.'/layout_bottom.php'; ?>
